spring:
  application:
    name: order-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.4-mini
          temperature: 0.1
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        collection-name: order-rules
        initialize-schema: true
  datasource:
    url: jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring.json.trusted.packages: "geeziel.events"

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    org.springframework.ai: TRACE
    org.springframework.web.client: TRACE
    org.springframework.web.reactive.function.client: TRACE

grpc:
  payment:
    host: ${GRPC_PAYMENT_HOST:localhost}
    port: ${GRPC_PAYMENT_PORT:9090}